# WAP to eight number from user and display all the unique numbers

s = set()
n1 = int(input("Enter the first number: "))
s.add(n1)
n2 = int(input("Enter the second number: "))
s.add(n2)
n3 = int(input("Enter the third number: "))
s.add(n3)
n4 = int(input("Enter the fourth number: "))
s.add(n4)
n5 = int(input("Enter the fifth number: "))
s.add(n5)
n6 = int(input("Enter the sixth number: "))
s.add(n6)
n7 = int(input("Enter the seventh number: "))
s.add(n7)
n8 = int(input("Enter the eighth number: "))
s.add(n8)
print(s)
print(type(s))

